const products = [
  {
    id: 1,
    name: 'UltraMax Li-Ion Battery',
    price: 59.99,
    description: 'The UltraMax Li-Ion Battery delivers high-capacity power for smartphones and laptops. Engineered with advanced overcharge protection and fast-charging technology, this sleek, durable battery ensures reliable performance for demanding users. Perfect for on-the-go professionals and tech enthusiasts.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.5,
    isBestSeller: true,
    specifications: [
      { label: 'Capacity', value: '5000 mAh' },
      { label: 'Output', value: '18W Fast Charging' },
      { label: 'Input', value: 'USB-C' },
      { label: 'Dimensions', value: '5.2 x 2.5 x 0.5 inches' },
      { label: 'Weight', value: '6.7 oz' },
      { label: 'Material', value: 'Aluminum Alloy' },
    ],
    features: [
      'Advanced overcharge protection for safety',
      '18W fast charging for quick power-ups',
      'Sleek, lightweight aluminum design',
      'LED charge indicator',
    ],
    compatibility: ['iPhone 12 and newer', 'Samsung Galaxy S21 and newer', 'Most USB-C laptops'],
    warranty: '2-year limited warranty, 30-day money-back guarantee',
    faqs: [
      { question: 'Does this support wireless charging?', answer: 'No, this is a wired battery pack requiring a USB-C cable.' },
      { question: 'Can it charge a laptop?', answer: 'Yes, it supports USB-C laptops with up to 18W power delivery.' },
    ],
    reviews: [
      { id: 1, author: 'Alice Brown', rating: 4.5, comment: 'This battery charges my phone so quickly! Very reliable and compact.', date: '2025-06-10' },
      { id: 2, author: 'Mark Wilson', rating: 4.0, comment: 'Good performance, but the price is a bit high for the capacity.', date: '2025-06-05' },
    ],
    relatedProducts: [3, 6, 11],
  },
  {
    id: 2,
    name: 'QuickCharge USB-C Adapter',
    price: 29.99,
    description: 'The QuickCharge USB-C Adapter is a compact 65W charger designed for multiple devices. With a durable braided cable and Power Delivery support, it ensures fast, efficient charging for smartphones, tablets, and laptops. Ideal for home or travel use.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.0,
    isBestSeller: false,
    specifications: [
      { label: 'Power Output', value: '65W' },
      { label: 'Ports', value: '1 USB-C' },
      { label: 'Cable Length', value: '6 ft' },
      { label: 'Dimensions', value: '2.1 x 2.1 x 1.1 inches' },
      { label: 'Weight', value: '4.2 oz' },
      { label: 'Compatibility', value: 'USB-C Devices' },
    ],
    features: [
      '65W Power Delivery for rapid charging',
      'Durable braided USB-C cable included',
      'Compact design for portability',
      'Overheat and short-circuit protection',
    ],
    compatibility: ['MacBook Air/Pro', 'iPad Pro', 'Samsung Galaxy series', 'Nintendo Switch'],
    warranty: '1-year warranty, 30-day return policy',
    faqs: [
      { question: 'Is the cable detachable?', answer: 'Yes, the included USB-C cable is detachable.' },
      { question: 'Can it charge multiple devices?', answer: 'It has one port, so it charges one device at a time.' },
    ],
    reviews: [
      { id: 1, author: 'Sarah Lee', rating: 4.0, comment: 'Works great with my laptop and phone. Cable feels sturdy.', date: '2025-05-20' },
      { id: 2, author: 'Tom Clark', rating: 3.8, comment: 'Fast charging, but it gets warm during use.', date: '2025-05-15' },
    ],
    relatedProducts: [12, 13, 16],
  },
  {
    id: 3,
    name: 'PowerCore 10,000mAh Bank',
    price: 39.99,
    description: 'The PowerCore 10,000mAh Bank is a portable powerhouse with dual USB ports, perfect for travel. Featuring LED indicators and a compact design, it’s ideal for charging smartphones and tablets on the go. A must-have for frequent travelers.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    isBestSeller: true,
    specifications: [
      { label: 'Capacity', value: '10,000 mAh' },
      { label: 'Output', value: '2x USB-A (12W)' },
      { label: 'Input', value: 'Micro-USB' },
      { label: 'Dimensions', value: '5.8 x 2.8 x 0.6 inches' },
      { label: 'Weight', value: '7.5 oz' },
      { label: 'Features', value: 'LED Indicators' },
    ],
    features: [
      'Dual USB-A ports for multi-device charging',
      'Compact and lightweight for travel',
      'LED battery status indicators',
      'Surge protection for device safety',
    ],
    compatibility: ['Most smartphones', 'Tablets', 'Bluetooth devices'],
    warranty: '18-month warranty, 30-day money-back guarantee',
    faqs: [
      { question: 'Can it charge two devices at once?', answer: 'Yes, it has two USB-A ports for simultaneous charging.' },
      { question: 'Does it support fast charging?', answer: 'It supports up to 12W charging, not full fast-charging standards.' },
    ],
    reviews: [
      { id: 1, author: 'Emily Davis', rating: 5.0, comment: 'Best power bank I’ve owned! Charges my devices multiple times.', date: '2025-06-12' },
      { id: 2, author: 'James Taylor', rating: 4.5, comment: 'Very portable and reliable. Highly recommend for travel.', date: '2025-06-08' },
    ],
    relatedProducts: [1, 7, 11],
  },
  {
    id: 4,
    name: 'EcoSolar Charger Kit',
    price: 79.99,
    description: 'The EcoSolar Charger Kit is a 20W solar charger with a built-in battery, designed for outdoor adventures. Its water-resistant, rugged build makes it perfect for camping, hiking, and off-grid charging. Eco-friendly and reliable.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.2,
    isBestSeller: false,
    specifications: [
      { label: 'Power Output', value: '20W' },
      { label: 'Battery Capacity', value: '5000 mAh' },
      { label: 'Ports', value: '1 USB-A, 1 USB-C' },
      { label: 'Dimensions', value: '7.0 x 4.0 x 1.2 inches' },
      { label: 'Weight', value: '12.3 oz' },
      { label: 'Protection', value: 'IP65 Water-Resistant' },
    ],
    features: [
      'High-efficiency solar panels',
      'IP65 water-resistant rating',
      'Dual USB ports for versatile charging',
      'Built-in 5000mAh battery',
    ],
    compatibility: ['Smartphones', 'Tablets', 'GPS devices', 'Action cameras'],
    warranty: '1-year warranty, 30-day return policy',
    faqs: [
      { question: 'How long does solar charging take?', answer: 'Full charge in 8-10 hours under direct sunlight.' },
      { question: 'Is it waterproof?', answer: 'It’s IP65 water-resistant, suitable for light rain but not submersion.' },
    ],
    reviews: [
      { id: 1, author: 'Chris Green', rating: 4.0, comment: 'Great for camping, but charging speed depends on sunlight.', date: '2025-05-25' },
      { id: 2, author: 'Lisa Adams', rating: 4.5, comment: 'Durable and eco-friendly. Perfect for outdoor trips.', date: '2025-05-18' },
    ],
    relatedProducts: [14, 17, 19],
  },
  {
    id: 5,
    name: 'MegaVolt AA Battery Pack',
    price: 19.99,
    description: 'The MegaVolt AA Battery Pack offers rechargeable AA batteries optimized for high-drain devices like cameras and toys. With a long cycle life and consistent performance, it’s a cost-effective choice for households and professionals.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.3,
    isBestSeller: false,
    specifications: [
      { label: 'Type', value: 'AA Rechargeable' },
      { label: 'Capacity', value: '2500 mAh' },
      { label: 'Quantity', value: '4 per pack' },
      { label: 'Cycle Life', value: 'Up to 1000 cycles' },
      { label: 'Voltage', value: '1.2V' },
      { label: 'Charger Compatibility', value: 'Standard NiMH Chargers' },
    ],
    features: [
      'High capacity for high-drain devices',
      'Up to 1000 recharge cycles',
      'Eco-friendly alternative to disposables',
      'Consistent power output',
    ],
    compatibility: ['Digital cameras', 'Toys', 'Game controllers', 'Flashlights'],
    warranty: '1-year warranty, 30-day money-back guarantee',
    faqs: [
      { question: 'Do these require a special charger?', answer: 'No, they work with standard NiMH battery chargers.' },
      { question: 'Are they pre-charged?', answer: 'Yes, they come partially pre-charged and ready to use.' },
    ],
    reviews: [
      { id: 1, author: 'David Miller', rating: 4.5, comment: 'Perfect for my camera. Lasts much longer than disposables.', date: '2025-06-01' },
      { id: 2, author: 'Anna White', rating: 4.0, comment: 'Good value, but charging takes a while.', date: '2025-05-28' },
    ],
    relatedProducts: [9, 18, 20],
  },
  {
    id: 6,
    name: 'ThunderHub Multi-Port Charger',
    price: 49.99,
    description: 'The ThunderHub Multi-Port Charger allows simultaneous charging of multiple devices with its smart charging technology. Compact and efficient, it’s perfect for home or office use.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    isBestSeller: true,
    specifications: [
      { label: 'Power Output', value: '60W' },
      { label: 'Ports', value: '3 USB-A, 1 USB-C' },
      { label: 'Dimensions', value: '3.0 x 2.5 x 1.0 inches' },
      { label: 'Weight', value: '5.6 oz' },
      { label: 'Features', value: 'Smart Charge Detection' },
      { label: 'Cable Included', value: 'No' },
    ],
    features: [
      'Charges up to four devices at once',
      'Smart charge detection for optimal power',
      'Compact design for desk or travel',
      'Overcurrent protection',
    ],
    compatibility: ['Smartphones', 'Tablets', 'Laptops', 'Smartwatches'],
    warranty: '2-year warranty, 30-day return policy',
    faqs: [
      { question: 'Does it include cables?', answer: 'No, cables are not included and must be purchased separately.' },
      { question: 'Can it charge a MacBook?', answer: 'Yes, the USB-C port supports up to 60W for MacBook charging.' },
    ],
    reviews: [
      { id: 1, author: 'Mike Johnson', rating: 4.8, comment: 'Charges everything at once! A game-changer for my desk.', date: '2025-06-15' },
      { id: 2, author: 'Laura King', rating: 4.5, comment: 'Very convenient, but the ports are a bit tight.', date: '2025-06-10' },
    ],
    relatedProducts: [2, 10, 16],
  },
  {
    id: 7,
    name: 'SlimFit Power Bank',
    price: 29.99,
    description: 'The SlimFit Power Bank is an ultra-slim 5,000mAh charger designed for pocket-sized convenience. Perfect for daily commutes and quick top-ups.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.1,
    isBestSeller: false,
    specifications: [
      { label: 'Capacity', value: '5,000 mAh' },
      { label: 'Output', value: '15W' },
      { label: 'Input', value: 'USB-C' },
      { label: 'Dimensions', value: '5.0 x 2.5 x 0.3 inches' },
      { label: 'Weight', value: '4.8 oz' },
      { label: 'Material', value: 'Polycarbonate' },
    ],
    features: [
      'Ultra-slim design for portability',
      '15W output for fast charging',
      'Durable polycarbonate shell',
      'Built-in USB-C cable',
    ],
    compatibility: ['Smartphones', 'Wireless earbuds', 'Smartwatches'],
    warranty: '1-year warranty, 30-day money-back guarantee',
    faqs: [
      { question: 'Is the USB-C cable detachable?', answer: 'No, the cable is built-in for convenience.' },
      { question: 'Can it charge tablets?', answer: 'It can charge tablets but may not fully charge larger models.' },
    ],
    reviews: [
      { id: 1, author: 'Rachel Lee', rating: 4.0, comment: 'Super slim and easy to carry, but capacity is limited.', date: '2025-05-22' },
      { id: 2, author: 'Paul Harris', rating: 4.2, comment: 'Great for quick top-ups during the day.', date: '2025-05-19' },
    ],
    relatedProducts: [3, 11, 17],
  },
  {
    id: 8,
    name: 'ProCharge Wireless Pad',
    price: 44.99,
    description: 'The ProCharge Wireless Pad is a Qi-certified charger with fast-charge support for smartphones. Its sleek design and non-slip surface ensure secure and efficient charging.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.4,
    isBestSeller: false,
    specifications: [
      { label: 'Power Output', value: '15W' },
      { label: 'Compatibility', value: 'Qi-enabled Devices' },
      { label: 'Dimensions', value: '3.9 x 3.9 x 0.4 inches' },
      { label: 'Weight', value: '3.2 oz' },
      { label: 'Features', value: 'Non-slip Surface' },
      { label: 'Cable Included', value: 'Yes (USB-C)' },
    ],
    features: [
      'Fast 15W wireless charging',
      'Non-slip surface for stability',
      'Slim and modern design',
      'LED charging indicator',
    ],
    compatibility: ['iPhone 8 and newer', 'Samsung Galaxy S10 and newer', 'Qi-enabled devices'],
    warranty: '1-year warranty, 30-day return policy',
    faqs: [
      { question: 'Does it work with phone cases?', answer: 'Yes, it works with cases up to 5mm thick.' },
      { question: 'Is it compatible with AirPods?', answer: 'Yes, it charges AirPods with a wireless charging case.' },
    ],
    reviews: [
      { id: 1, author: 'Kelly Moore', rating: 4.5, comment: 'Love the wireless convenience. Works perfectly with my phone.', date: '2025-06-03' },
      { id: 2, author: 'Sam Carter', rating: 4.0, comment: 'Good charger, but alignment can be tricky.', date: '2025-05-30' },
    ],
    relatedProducts: [19, 2, 13],
  },
  {
    id: 9,
    name: 'EnduraCell AAA Batteries',
    price: 15.99,
    description: 'The EnduraCell AAA Batteries provide long-lasting power for remotes, clocks, and small electronics. Reliable and cost-effective for everyday use.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.0,
    isBestSeller: false,
    specifications: [
      { label: 'Type', value: 'AAA Alkaline' },
      { label: 'Quantity', value: '8 per pack' },
      { label: 'Voltage', value: '1.5V' },
      { label: 'Shelf Life', value: 'Up to 7 years' },
      { label: 'Applications', value: 'Low-drain Devices' },
      { label: 'Recyclable', value: 'Yes' },
    ],
    features: [
      'Long shelf life for storage',
      'Reliable power for low-drain devices',
      'Leak-resistant design',
      'Eco-friendly recyclable materials',
    ],
    compatibility: ['TV remotes', 'Clocks', 'Wireless keyboards', 'Mice'],
    warranty: '1-year warranty, 30-day return policy',
    faqs: [
      { question: 'Are these rechargeable?', answer: 'No, these are single-use alkaline batteries.' },
      { question: 'Can they be used in high-drain devices?', answer: 'They’re best suited for low-drain devices like remotes.' },
    ],
    reviews: [
      { id: 1, author: 'Nancy Young', rating: 4.0, comment: 'Work well in my TV remote. Good value for the price.', date: '2025-05-27' },
      { id: 2, author: 'George Allen', rating: 3.8, comment: 'Decent batteries, but not as long-lasting as premium brands.', date: '2025-05-24' },
    ],
    relatedProducts: [5, 18, 20],
  },
  {
    id: 10,
    name: 'TurboVolt Car Charger',
    price: 24.99,
    description: 'The TurboVolt Car Charger offers dual-port 30W charging for phones and tablets on the go. Compact and reliable, it’s perfect for road trips.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.3,
    isBestSeller: true,
    specifications: [
      { label: 'Power Output', value: '30W' },
      { label: 'Ports', value: '1 USB-A, 1 USB-C' },
      { label: 'Dimensions', value: '2.0 x 1.0 x 0.8 inches' },
      { label: 'Weight', value: '1.6 oz' },
      { label: 'Compatibility', value: 'Most Devices' },
      { label: 'Features', value: 'Overheat Protection' },
    ],
    features: [
      'Dual ports for simultaneous charging',
      '30W fast charging capability',
      'Compact design for car outlets',
      'Built-in safety protections',
    ],
    compatibility: ['Smartphones', 'Tablets', 'GPS devices'],
    warranty: '1-year warranty, 30-day money-back guarantee',
    faqs: [
      { question: 'Does it support fast charging?', answer: 'Yes, the USB-C port supports up to 30W fast charging.' },
      { question: 'Will it fit all car outlets?', answer: 'It’s designed to fit standard 12V/24V car outlets.' },
    ],
    reviews: [
      { id: 1, author: 'Robert Lee', rating: 4.5, comment: 'Charges my phone quickly in the car. Very compact.', date: '2025-06-07' },
      { id: 2, author: 'Lisa Brown', rating: 4.0, comment: 'Works well, but the USB-A port is a bit slow.', date: '2025-06-04' },
    ],
    relatedProducts: [2, 6, 13],
  },
  {
    id: 11,
    name: 'PowerPlus 20,000mAh Bank',
    price: 59.99,
    description: 'The PowerPlus 20,000mAh Bank is a high-capacity power bank with USB-C and USB-A ports, ideal for extended trips and multiple device charging.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    isBestSeller: true,
    specifications: [
      { label: 'Capacity', value: '20,000 mAh' },
      { label: 'Output', value: '2 USB-A (18W), 1 USB-C (20W)' },
      { label: 'Input', value: 'USB-C, MicroUSB' },
      { label: 'Dimensions', value: '6.2 x 3.0 x 0.8 inches' },
      { label: 'Weight', value: '13.4 oz' },
      { label: 'Features', value: 'LED Display' },
    ],
    features: [
      'High capacity for multiple charges',
      'Fast charging via USB-C and USB-A',
      'LED display for battery status',
      'Multi-device compatibility',
    ],
    compatibility: ['Smartphones', 'Tablets', 'Laptops', 'Cameras'],
    warranty: '2-year warranty, 30-day return policy',
    faqs: [
      { question: 'Can it charge a laptop?', answer: 'Yes, it supports laptops with USB-C charging up to 20W.' },
      { question: 'How long does it take to recharge?', answer: 'Approximately 6-8 hours with a 20W charger.' },
    ],
    reviews: [
      { id: 1, author: 'Sophie Turner', rating: 5.0, comment: 'Amazing capacity! Charges my tablet and phone multiple times.', date: '2025-06-14' },
      { id: 2, author: 'Daniel Kim', rating: 4.5, comment: 'A bit bulky but worth it for the power.', date: '2025-06-09' },
    ],
    relatedProducts: [1, 3, 7],
  },
  {
    id: 12,
    name: 'SmartCharge Wall Adapter',
    price: 27.99,
    description: 'The SmartCharge Wall Adapter uses auto-detect technology for optimal charging of phones and tablets. Compact and efficient for daily use.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.2,
    isBestSeller: false,
    specifications: [
      { label: 'Power Output', value: '30W' },
      { label: 'Ports', value: '1 USB-C' },
      { label: 'Dimensions', value: '2.2 x 1.8 x 1.0 inch' },
      { label: 'Weight', value: '3.5 oz' },
      { label: 'Features', value: 'Auto-Detect Technology' },
      { label: 'Cable Included', value: 'No' },
    ],
    features: [
      'Auto-detect for optimized charging',
      '30W fast charging support',
      'Compact and travel-friendly',
      'Safety protections included',
    ],
    compatibility: ['Smartphones', 'Tablets', 'USB-C devices'],
    warranty: '1-year warranty, 30-day return policy',
    faqs: [
      { question: 'Does it come with a cable?', answer: 'No, a USB-C cable must be purchased separately.' },
      { question: 'Can it charge laptops?', answer: 'It supports some laptops with up to 30W USB-C charging.' },
    ],
    reviews: [
      { id: 1, author: 'Emma Stone', rating: 4.0, comment: 'Reliable charger, adjusts power nicely.', date: '2025-05-21' },
      { id: 2, author: 'Jack Lee', rating: 4.3, comment: 'Good for travel, but wish it had a cable included.', date: '2025-05-16' },
    ],
    relatedProducts: [2, 10, 13],
  },
  {
    id: 13,
    name: 'FlexiCord USB-C Cable',
    price: 12.99,
    description: 'The FlexiCord USB-C Cable is a durable 6ft cable with reinforced connectors, designed for daily charging and data transfer.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.0,
    isBestSeller: false,
    specifications: [
      { label: 'Length', value: '6 ft' },
      { label: 'Type', value: 'USB-C to USB-C' },
      { label: 'Data Transfer Speed', value: 'Up to 60 MB/s' },
      { label: 'Power Delivery', value: 'Up to 100W' },
      { label: 'Material', value: 'Nylon Braided' },
      { label: 'Durability', value: '10,000+ Bends' },
    ],
    features: [
      'Nylon braided for durability',
      '100W power delivery support',
      'Fast data transfer speeds',
      'Reinforced connectors',
    ],
    compatibility: ['USB-C smartphones', 'Laptops', 'Tablets', 'Chargers'],
    warranty: '1-year warranty, 30-day return policy',
    faqs: [
      { question: 'Does it support fast charging?', answer: 'Yes, it supports up to 100W power delivery.' },
      { question: 'Is it compatible with Thunderbolt?', answer: 'No, it’s designed for USB-C charging and data transfer.' },
    ],
    reviews: [
      { id: 1, author: 'Olivia Smith', rating: 4.2, comment: 'Strong cable, doesn’t fray easily.', date: '2025-05-26' },
      { id: 2, author: 'Ethan Brown', rating: 3.8, comment: 'Good for charging, but data transfer is average.', date: '2025-05-23' },
    ],
    relatedProducts: [2, 8, 12],
  },
  {
    id: 14,
    name: 'EcoPower Solar Battery',
    price: 89.99,
    description: 'The EcoPower Solar Battery is a solar-powered 10,000mAh pack for eco-conscious charging in remote areas. Rugged and efficient for outdoor use.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.5,
    isBestSeller: false,
    specifications: [
      { label: 'Power Output', value: '15W' },
      { label: 'Battery Capacity', value: '10,000 mAh' },
      { label: 'Ports', value: '2 USB-A' },
      { label: 'Dimensions', value: '6.5 x 3.5 x 1.0 inch' },
      { label: 'Weight', value: '14.1 oz' },
      { label: 'Protection', value: 'IP67 Waterproof' },
    ],
    features: [
      'Solar-powered charging',
      'IP67 waterproof and dustproof',
      'High-capacity battery',
      'Dual USB-A ports',
    ],
    compatibility: ['Smartphones', 'Tablets', 'GPS devices', 'Camping gear'],
    warranty: '1-year warranty, 30-day return policy',
    faqs: [
      { question: 'Is it fully waterproof?', answer: 'Yes, it’s IP67 rated and can be submerged up to 1 meter for 30 minutes.' },
      { question: 'How efficient is solar charging?', answer: 'It takes 10-12 hours in direct sunlight for a full charge.' },
    ],
    reviews: [
      { id: 1, author: 'Liam Walker', rating: 4.5, comment: 'Perfect for hiking. Solar charging is a bonus!', date: '2025-06-02' },
      { id: 2, author: 'Mia Chen', rating: 4.0, comment: 'Great concept, but heavy for backpacking.', date: '2025-05-29' },
    ],
    relatedProducts: [4, 17, 19],
  },
  {
    id: 15,
    name: 'MiniVolt Micro-USB Charger',
    price: 19.99,
    description: 'The MiniVolt Micro-USB Charger is a compact charger for older devices, offering reliable performance in a small package.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.1,
    isBestSeller: false,
    specifications: [
      { label: 'Power Output', value: '10W' },
      { label: 'Ports', value: '1 Micro-USB' },
      { label: 'Dimensions', value: '1.5 x 1.5 x 0.8 inches' },
      { label: 'Weight', value: '1.8 oz' },
      { label: 'Compatibility', value: 'Micro-USB Devices' },
      { label: 'Cable Included', value: 'Yes (3 ft)' },
    ],
    features: [
      'Compact size for portability',
      'Reliable 10W charging',
      'Includes 3ft Micro-USB cable',
      'Overcharge protection',
    ],
    compatibility: ['Older smartphones', 'E-readers', 'Bluetooth speakers'],
    warranty: '1-year warranty, 30-day return policy',
    faqs: [
      { question: 'Does it support fast charging?', answer: 'No, it provides standard 10W charging.' },
      { question: 'Is the cable detachable?', answer: 'Yes, the Micro-USB cable is detachable.' },
    ],
    reviews: [
      { id: 1, author: 'Ava Lopez', rating: 4.0, comment: 'Works well with my old tablet. Compact size.', date: '2025-05-20' },
      { id: 2, author: 'Noah Scott', rating: 4.2, comment: 'Good for the price, but charging is slow.', date: '2025-05-17' },
    ],
    relatedProducts: [2, 10, 12],
  },
  {
    id: 16,
    name: 'HyperCharge 100W Charger',
    price: 59.99,
    description: 'The HyperCharge 100W Charger is a high-power USB-C charger for laptops, tablets, and phones, featuring ultra-fast charging and a compact design.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    isBestSeller: true,
    specifications: [
      { label: 'Power Output', value: '100W' },
      { label: 'Ports', value: '1 USB-C' },
      { label: 'Dimensions', value: '2.8 x 2.5 x 1.2 inches' },
      { label: 'Weight', value: '6.0 oz' },
      { label: 'Compatibility', value: 'USB-C Devices' },
      { label: 'Features', value: 'GaN Technology' },
    ],
    features: [
      '100W ultra-fast charging',
      'Gallium Nitride (GaN) technology',
      'Compact and lightweight',
      'Multiple safety protections',
    ],
    compatibility: ['MacBook Pro', 'Dell XPS', 'Smartphones', 'Tablets'],
    warranty: '2-year warranty, 30-day return policy',
    faqs: [
      { question: 'Does it include a cable?', answer: 'No, a USB-C cable is not included.' },
      { question: 'Can it charge older USB-A devices?', answer: 'Yes, with a USB-C to USB-A adapter or cable.' },
    ],
    reviews: [
      { id: 1, author: 'Ella Parker', rating: 4.8, comment: 'Charges my laptop in no time! Highly recommend.', date: '2025-06-13' },
      { id: 2, author: 'Lucas Gray', rating: 4.5, comment: 'Powerful and compact, but a bit pricey.', date: '2025-06-08' },
    ],
    relatedProducts: [2, 6, 12],
  },
  {
    id: 17,
    name: 'TravelMate Power Bank',
    price: 49.99,
    description: 'The TravelMate Power Bank is a 15,000mAh charger with a foldable plug, designed for easy travel and versatile charging.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.4,
    isBestSeller: false,
    specifications: [
      { label: 'Capacity', value: '15,000 mAh' },
      { label: 'Output', value: '2 USB-A (15W)' },
      { label: 'Input', value: 'Built-in AC Plug' },
      { label: 'Dimensions', value: '5.9 x 2.9 x 0.7 inches' },
      { label: 'Weight', value: '10.2 oz' },
      { label: 'Features', value: 'Foldable Plug' },
    ],
    features: [
      'Foldable AC plug for easy charging',
      '15,000mAh capacity for multiple charges',
      'Dual USB-A ports',
      'Travel-friendly design',
    ],
    compatibility: ['Smartphones', 'Tablets', 'Wireless earbuds'],
    warranty: '1-year warranty, 30-day return policy',
    faqs: [
      { question: 'Can the plug be used internationally?', answer: 'Yes, with a compatible voltage converter.' },
      { question: 'Does it support fast charging?', answer: 'It provides up to 15W, suitable for standard charging.' },
    ],
    reviews: [
      { id: 1, author: 'Grace Kim', rating: 4.5, comment: 'Love the built-in plug! Great for travel.', date: '2025-06-05' },
      { id: 2, author: 'Henry Ford', rating: 4.0, comment: 'Convenient, but a bit heavy.', date: '2025-06-01' },
    ],
    relatedProducts: [3, 7, 11],
  },
  {
    id: 18,
    name: 'DuraCell 9V Battery',
    price: 22.99,
    description: 'The DuraCell 9V Battery is reliable for smoke detectors, professional equipment, and other high-drain devices. Long-lasting and dependable.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.2,
    isBestSeller: false,
    specifications: [
      { label: 'Type', value: '9V Alkaline' },
      { label: 'Quantity', value: '2 per pack' },
      { label: 'Voltage', value: '9V' },
      { label: 'Shelf Life', value: 'Up to 5 years' },
      { label: 'Applications', value: 'High-drain Devices' },
      { label: 'Recyclable', value: 'Yes' },
    ],
    features: [
      'Long-lasting power for critical devices',
      '5-year shelf life',
      'Leak-resistant technology',
      'Recyclable materials',
    ],
    compatibility: ['Smoke detectors', 'Multimeters', 'Microphones'],
    warranty: '1-year warranty, 30-day return policy',
    faqs: [
      { question: 'Are these rechargeable?', answer: 'No, these are single-use alkaline batteries.' },
      { question: 'Can they be used in medical devices?', answer: 'Yes, if the device requires a standard 9V battery.' },
    ],
    reviews: [
      { id: 1, author: 'Isabella Ross', rating: 4.0, comment: 'Works great in my smoke detector.', date: '2025-05-25' },
      { id: 2, author: 'Mason Lee', rating: 4.3, comment: 'Reliable, but a bit expensive.', date: '2025-05-22' },
    ],
    relatedProducts: [5, 9, 20],
  },
  {
    id: 19,
    name: 'SwiftCharge Wireless Stand',
    price: 39.99,
    description: 'The SwiftCharge Wireless Stand offers adjustable angles and fast charging for phones and earbuds, perfect for desks or nightstands.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.3,
    isBestSeller: false,
    specifications: [
      { label: 'Power Output', value: '10W' },
      { label: 'Compatibility', value: 'Qi-enabled Devices' },
      { label: 'Dimensions', value: '4.5 x 3.5 x 5.0 inches' },
      { label: 'Weight', value: '5.8 oz' },
      { label: 'Features', value: 'Adjustable Angle' },
      { label: 'Cable Included', value: 'Yes (USB-C)' },
    ],
    features: [
      'Adjustable stand for versatile use',
      '10W fast wireless charging',
      'Non-slip base for stability',
      'Sleek design for home or office',
    ],
    compatibility: ['iPhone X and newer', 'Samsung Galaxy S9 and newer', 'AirPods Pro'],
    warranty: '1-year warranty, 30-day return policy',
    faqs: [
      { question: 'Can it charge through a case?', answer: 'Yes, it works with cases up to 4mm thick.' },
      { question: 'Does it support landscape charging?', answer: 'Yes, the adjustable angle supports both portrait and landscape.' },
    ],
    reviews: [
      { id: 1, author: 'Charlotte Evans', rating: 4.5, comment: 'Love the adjustable stand. Great for video calls.', date: '2025-06-04' },
      { id: 2, author: 'Benjamin Hill', rating: 4.0, comment: 'Works well, but charging speed could be faster.', date: '2025-05-31' },
    ],
    relatedProducts: [8, 2, 13],
  },
  {
    id: 20,
    name: 'MaxPower Battery Bundle',
    price: 99.99,
    description: 'The MaxPower Battery Bundle includes AA, AAA, and 9V batteries, perfect for all your household and professional needs. Long-lasting and reliable.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    isBestSeller: true,
    specifications: [
      { label: 'Contents', value: '8 AA, 8 AAA, 2 9V' },
      { label: 'Type', value: 'Alkaline' },
      { label: 'Voltage', value: '1.5V (AA/AAA), 9V' },
      { label: 'Shelf Life', value: 'Up to 7 years' },
      { label: 'Applications', value: 'Various Devices' },
      { label: 'Recyclable', value: 'Yes' },
    ],
    features: [
      'Comprehensive battery assortment',
      'Long shelf life for storage',
      'Reliable power for all devices',
      'Eco-friendly recyclable packaging',
    ],
    compatibility: ['Toys', 'Remotes', 'Smoke detectors', 'Flashlights'],
    warranty: '1-year warranty, 30-day return policy',
    faqs: [
      { question: 'Are the batteries rechargeable?', answer: 'No, these are single-use alkaline batteries.' },
      { question: 'Is the packaging recyclable?', answer: 'Yes, the packaging is made from recyclable materials.' },
    ],
    reviews: [
      { id: 1, author: 'Amelia Wright', rating: 5.0, comment: 'Perfect bundle for my home. Great value!', date: '2025-06-11' },
      { id: 2, author: 'William Scott', rating: 4.5, comment: 'Covers all my battery needs. Highly recommend.', date: '2025-06-06' },
    ],
    relatedProducts: [5, 9, 18],
  },
];

export default products;